const clc = require('cli-color')

module.exports.greenOnBlack = clc.xterm(47).bgXterm(0)
module.exports.redOnBlack = clc.xterm(196).bgXterm(0)
module.exports.yellowOnBlack = clc.xterm(11).bgXterm(0)
module.exports.cyanOnBlack = clc.xterm(14).bgXterm(0)
module.exports.blackBG = clc.bgXterm(0)
module.exports.blackOnRed = clc.xterm(15).bgXterm(124)
module.exports.cyan = clc.xterm(14)
module.exports.yellow = clc.xterm(11)
module.exports.white = clc.xterm(15)
